name: LAPRAS Card

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-card:
    name: LAPRAS Card
    runs-on: ubuntu-latest
    steps:
      - uses: kawamataryo/lapras-card-readme@main
        with:
          SHARE_ID: "Isekiryu"
          ICON_FIRST: "#ffffff"
          ICON_SECOND: "#080202"
          BACKGROUND_FIRST: "#000000"
          BACKGROUND_SECOND: "#e1e1e1"
          LANG: "ja"
